name = "BondGraphs"
uuid = "d1a4f103-cd9c-465b-aef3-7f12ef11bc98"
authors = ["Jedforrest <jedforrest@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
